CREATE TABLE IF NOT EXISTS public.bc_roster_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id text NOT NULL,
  source_session_id text NOT NULL,
  day text,
  time text,
  label text,
  captured_at timestamptz NOT NULL DEFAULT now(),
  source_updated_at timestamptz,
  team_layout jsonb NOT NULL DEFAULT '[]'::jsonb,
  teams jsonb NOT NULL DEFAULT '{}'::jsonb,
  team_attack1 jsonb NOT NULL DEFAULT '[]'::jsonb,
  team_attack2 jsonb NOT NULL DEFAULT '[]'::jsonb,
  team_defense jsonb NOT NULL DEFAULT '[]'::jsonb,
  team_forest jsonb NOT NULL DEFAULT '[]'::jsonb,
  waiting_list jsonb NOT NULL DEFAULT '[]'::jsonb,
  team_sizes jsonb NOT NULL DEFAULT '{}'::jsonb,
  team_names jsonb NOT NULL DEFAULT '{}'::jsonb,
  leader_ids jsonb NOT NULL DEFAULT '{}'::jsonb,
  source text
);

ALTER TABLE public.bc_roster_snapshots
  ADD COLUMN IF NOT EXISTS guild_id text,
  ADD COLUMN IF NOT EXISTS source_session_id text,
  ADD COLUMN IF NOT EXISTS day text,
  ADD COLUMN IF NOT EXISTS time text,
  ADD COLUMN IF NOT EXISTS label text,
  ADD COLUMN IF NOT EXISTS captured_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS source_updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS team_layout jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS teams jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS team_attack1 jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS team_attack2 jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS team_defense jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS team_forest jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS waiting_list jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS team_sizes jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS team_names jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS leader_ids jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS source text;

CREATE UNIQUE INDEX IF NOT EXISTS bc_roster_snapshots_guild_source_session_uidx
  ON public.bc_roster_snapshots (guild_id, source_session_id);

CREATE INDEX IF NOT EXISTS bc_roster_snapshots_guild_captured_idx
  ON public.bc_roster_snapshots (guild_id, captured_at DESC);
